import { useState } from 'react'

export default function GananciasTab({ trabajos, ventas }) {
  const [open, setOpen] = useState(null)
  const service = trabajos.reduce((sum, t) => sum + Number(t.precio_cobrado || 0) - Number(t.costo_repuesto || 0), 0)
  const celulares = ventas.filter(v => v.categoria === 'celular').reduce((sum, v) => sum + Number(v.precio_venta || 0) - Number(v.costo_compra || 0), 0)
  const accesorios = ventas.filter(v => v.categoria === 'accesorio').reduce((sum, v) => sum + Number(v.precio_venta || 0) - Number(v.costo_compra || 0), 0)
  const total = service + celulares + accesorios
  const months = Array.from({ length: 6 }, (_, i) => { const d = new Date(); d.setMonth(d.getMonth() - (5 - i)); return { key: `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`, label: d.toLocaleDateString('es-AR', { month: 'short' }) } })
  const values = months.map(m => trabajos.filter(t => String(t.fecha).startsWith(m.key)).reduce((s, t) => s + Number(t.precio_cobrado || 0) - Number(t.costo_repuesto || 0), 0) + ventas.filter(v => String(v.fecha).startsWith(m.key)).reduce((s, v) => s + Number(v.precio_venta || 0) - Number(v.costo_compra || 0), 0))
  const max = Math.max(...values, 1)
  const records = [...trabajos.map(t => ({ id: `t-${t.id}`, fecha: t.fecha, tipo: 'Servicio técnico', detalle: `${t.cliente} · ${t.reparacion}`, cobrado: t.precio_cobrado, costo: t.costo_repuesto, extra: `Equipo: ${t.equipo || '—'} · Repuesto: ${t.repuesto || '—'}` })), ...ventas.map(v => ({ id: `v-${v.id}`, fecha: v.fecha, tipo: v.categoria === 'celular' ? 'Venta de celular' : 'Venta de accesorio', detalle: v.producto, cobrado: v.precio_venta, costo: v.costo_compra, extra: `Categoría: ${v.categoria}` }))].sort((a, b) => String(b.fecha).localeCompare(String(a.fecha)))
  return <div><h2 style={{ fontWeight: 800, fontSize: 18, marginBottom: 16 }}>Ganancias</h2><div className="stat-grid"><Stat label="Total" value={total} /><Stat label="Servicio técnico" value={service} /><Stat label="Celulares" value={celulares} /><Stat label="Accesorios" value={accesorios} /></div><div className="earnings-chart"><h3>Ganancias por mes</h3><div className="chart-bars">{values.map((v, i) => <div className="chart-column" key={months[i].key}><span>${v.toLocaleString('es-AR')}</span><div className="chart-bar" style={{ height: `${Math.max(8, (v / max) * 150)}px` }} /><small>{months[i].label}</small></div>)}</div></div><div className="earnings-records"><h3>Registro de ganancias</h3>{records.length === 0 && <p style={{ color: '#6b6b8a' }}>Todavía no hay movimientos registrados.</p>}{records.map(r => { const gain = Number(r.cobrado || 0) - Number(r.costo || 0); return <div className="earning-record" key={r.id}><button className="earning-record-main" onClick={() => setOpen(open === r.id ? null : r.id)}><span><strong>{r.tipo}</strong><small>{new Date(`${r.fecha}T12:00:00`).toLocaleDateString('es-AR')} · {r.detalle}</small></span><b>${gain.toLocaleString('es-AR')}</b><span>{open === r.id ? '▲' : '▼'}</span></button>{open === r.id && <div className="earning-record-details"><span>{r.extra}</span><span>Cobrado: ${Number(r.cobrado || 0).toLocaleString('es-AR')}</span><span>Costo: ${Number(r.costo || 0).toLocaleString('es-AR')}</span></div>}</div>})}</div></div>
}
function Stat({ label, value }) { return <div className="stat-card"><div className="stat-label">{label}</div><div className="stat-value" style={{ fontSize: 22 }}>${value.toLocaleString('es-AR')}</div></div> }
